version: 0.1

environment_variables:
  plaintext:
    SHIPPABLE: "true"
    key: "value"

phases:
  install:
    commands:
    # Install latest LTS node
      - apt-get update
      - apt-get install -y curl git bzip2
      - curl -sL https://deb.nodesource.com/setup_6.x | bash -
      - apt-get install -y nodejs
      - node --version
    # Install NPM packages and build client from gulpfile
      - "cd client && npm install --silent && ./node_modules/.bin/gulp build && cd .."
    # Install Python dependencies
      - python --version
      - apt-get install -y libgeos-c1 libgeos-dev  # Required for shapely
      - pip install -r requirements.txt
  pre_build:
    commands:
    # Required to display test results in Shippable GUI
      - mkdir -p shippable/testresults
      - mkdir -p shippable/codecoverage
  build:
    commands:
    # JS Unit Tests
      - "cd tests/client && ../../client/node_modules/.bin/karma start ./karma.conf.js --single-run --browsers PhantomJS --reporters junit && cd ../.."
    # Run Python tests
      - nosetests ./tests/server --with-xunit --xunit-file ./shippable/testresults/unitresults.xml --with-coverage --cover-erase --cover-package=./server
      - coverage xml -o shippable/codecoverage/coverage.xml
  post_build:
    commands:
      # Run deploy script to manage deploy to appropriate environment
      - export BRANCH=$(git branch --contains $CODEBUILD_RESOLVED_SOURCE_VERSION)
      - chmod +x ./devops/ci/shippable_deploy.sh
      - ./devops/ci/shippable_deploy.sh
artifacts:
  files:
    - location
    - location
  discard-paths: yes
  base-directory: location
